# Generated by Django 5.2.8 on 2025-12-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_referral_code_user_balance_user_earnings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('payout', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
