# Generated by Django 5.2.8 on 2025-12-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='instructions',
            field=models.TextField(default='Follow the task instructions.'),
        ),
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.CharField(default='task.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='payout',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
