# Generated by Django 6.0.2 on 2026-02-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_task_instructions_task_link_alter_task_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='platforms',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='short_desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
