# Generated by Django 6.0.2 on 2026-02-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_product_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('membership', 'Membership')], default='normal', max_length=20),
        ),
    ]
