# Generated by Django 6.0.2 on 2026-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
