# Generated by Django 6.0.2 on 2026-02-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='proof',
            field=models.ImageField(default=None, upload_to='task_proofs/'),
            preserve_default=False,
        ),
    ]
