# Generated by Django 6.0.2 on 2026-02-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_taskcompletion_approved_taskcompletion_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='task_proofs/'),
        ),
    ]
